CREATE TABLE YELP_USER
(
    YELPING_SINCE DATE,
    FUNNY_VOTES NUMBER,
    USEFUL_VOTES NUMBER,
    COOL_VOTES NUMBER,
    REVIEW_COUNT NUMBER,
    USER_NAME VARCHAR2(255),
    USER_ID VARCHAR2(30),
    FANS NUMBER,
    AVERAGE_STARS FLOAT,
    U_TYPE VARCHAR2(10),
    HOT_COMPLIMENT NUMBER,
    MORE_COMPLIMENT NUMBER,
    PROFILE_COMPLIMENT NUMBER,
    CUTE_COMPLIMENT NUMBER,
    LIST_COMPLIMENT NUMBER,
    NOTE_COMPLIMENT NUMBER,
    PLAIN_COMPLIMENT NUMBER,
    COOL_COMPLIMENT NUMBER,
    FUNNY_COMPLIMENT NUMBER,
    WRITER_COMPLIMENT NUMBER,
    PHOTOS_COMPLIMENT NUMBER,
    PRIMARY KEY (USER_ID)
);
CREATE INDEX U_STARS ON YELP_USER(AVERAGE_STARS);
CREATE INDEX U_FANS ON YELP_USER(FANS);


CREATE TABLE FRIENDS
(
    USER_ID VARCHAR2(30),
    FRIEND_ID VARCHAR2(30),
    PRIMARY KEY (USER_ID,FRIEND_ID),
    FOREIGN KEY (USER_ID) REFERENCES YELP_USER (USER_ID) ON DELETE CASCADE
);

CREATE TABLE ELITE_YEARS
(
    USER_ID VARCHAR2(30),
    ELITE NUMBER,
    PRIMARY KEY (USER_ID,ELITE),
    FOREIGN KEY (USER_ID) REFERENCES YELP_USER (USER_ID) ON DELETE CASCADE
);

CREATE TABLE BUSINESS
(
    BID VARCHAR2(30),
    FULL_ADDRESS VARCHAR2(255),
    OPEN_NOW INT,
    CITY VARCHAR2(255),
    REVIEW_COUNT NUMBER,
    B_NAME VARCHAR2(255),
    NEIGHBORHOODS VARCHAR2(255),
    LONGITUDE FLOAT,
    STATE VARCHAR2(255),
    STARS FLOAT,
    LATITUDE FLOAT,
    B_TYPE VARCHAR2(20),
    PRIMARY KEY (BID)
);
CREATE INDEX B_STARS ON BUSINESS(STARS);
CREATE INDEX B_STATE ON BUSINESS(STATE);
CREATE INDEX B_CITY ON BUSINESS(CITY);

CREATE TABLE B_HOURS
(
    D_O_W VARCHAR2(20),
    FROM_H FLOAT,
    TO_H FLOAT,
    BID VARCHAR2(30),
    PRIMARY KEY (BID, D_O_W),
    FOREIGN KEY (BID) REFERENCES BUSINESS (BID) ON DELETE CASCADE
);


CREATE TABLE NEIGHBORHOODS
(
	N_NAME VARCHAR2(100),
	BID VARCHAR2(30),
	PRIMARY KEY (BID, N_NAME),
    FOREIGN KEY (BID) REFERENCES BUSINESS (BID) ON DELETE CASCADE
);

CREATE TABLE B_MAIN_CATEGORY
(
    C_NAME VARCHAR2(255),
    BID VARCHAR2(30),
    PRIMARY KEY (BID, C_NAME),
    FOREIGN KEY (BID) REFERENCES BUSINESS (BID) ON DELETE CASCADE
);

CREATE TABLE B_SUB_CATEGORY
(
    C_NAME VARCHAR2(255),
    BID VARCHAR2(30),
    PRIMARY KEY (BID, C_NAME),
    FOREIGN KEY (BID) REFERENCES BUSINESS (BID) ON DELETE CASCADE
);

CREATE TABLE B_ATTRIBUTES
(
    A_NAME VARCHAR2(255),
    BID VARCHAR2(30),
    PRIMARY KEY (BID, A_NAME),
    FOREIGN KEY (BID) REFERENCES BUSINESS (BID) ON DELETE CASCADE
);

CREATE TABLE CHECK_IN
(
    CI_DAY VARCHAR2(30),
    CI_HOUR NUMBER,
    CI_COUNT NUMBER,
    BID VARCHAR2(30),
    PRIMARY KEY (BID, CI_DAY, CI_COUNT, CI_HOUR),
    FOREIGN KEY (BID) REFERENCES BUSINESS (BID) ON DELETE CASCADE
);


CREATE TABLE REVIEWS
(
 REVIEW_ID VARCHAR2(30),
    USER_ID VARCHAR2(30),
    BID VARCHAR2(30),
    FUNNY_VOTE NUMBER,
    USEFUL_VOTE NUMBER,
    COOL_VOTE NUMBER,
    STARS NUMBER,
    R_DATE VARCHAR(20),
    R_TEXT CLOB,
    R_TYPE VARCHAR2(20),
    PRIMARY KEY (REVIEW_ID),
    FOREIGN KEY (BID) REFERENCES BUSINESS (BID) ON DELETE CASCADE,
    FOREIGN KEY (USER_ID) REFERENCES YELP_USER (USER_ID) ON DELETE CASCADE
);
CREATE INDEX R_STARS ON REVIEWS(STARS);
