DROP TABLE REVIEWS;
DROP TABLE CHECK_IN;
DROP TABLE NEIGHBORHOODS;
DROP TABLE B_ATTRIBUTES;
DROP TABLE B_MAIN_CATEGORY;
DROP TABLE B_SUB_CATEGORY;
DROP TABLE B_HOURS;
DROP TABLE BUSINESS;
DROP TABLE ELITE_YEARS;
DROP TABLE FRIENDS;
DROP TABLE YELP_USER;

DROP INDEX R_STARS;
DROP INDEX B_STARS;
DROP INDEX B_STATE;
DROP INDEX B_CITY;
DROP INDEX U_STARS;
DROP INDEX U_FANS;
